version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm ci && npx ts-node src/simple-server.ts"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev -- --host --port 3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    depends_on:
      - backend


